version: '3.8'

services:
  ms-questionnaire:
    image: ms-questionnaire
    container_name: ms-questionnaire
    build:
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    # depends_on:
    #   - mongodb
    # mongodb:
    #   image: mongo
    #   container_name: ms-questionnaire-mongodb
    #   ports:
    #     - "27018:27018"
    #   volumes:
    #     - ./data/db:/data/db
